# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOnasimagazin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_onasimagazin(self):
    self.driver.get("https://qahacking.guru/")
    self.driver.set_window_size(1024, 768)
    self.driver.find_element(By.CSS_SELECTOR, ".uk-navbar-nav > li:nth-child(1) > a").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("sss")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("iii")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("1@v.ru")
    self.driver.find_element(By.ID, "sex-1").click()
    self.driver.find_element(By.ID, "date").click()
    self.driver.find_element(By.ID, "date").send_keys("01-01-2023")
    self.driver.find_element(By.ID, "hobbies-checkbox-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-9:nth-child(6) #hobbies-checkbox-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-9:nth-child(6) #hobbies-checkbox-1").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uk-open:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Купить").click()
    self.driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
    self.driver.find_element(By.ID, "f_name").click()
    self.driver.find_element(By.ID, "f_name").send_keys("fff")
    self.driver.find_element(By.ID, "l_name").click()
    self.driver.find_element(By.ID, "l_name").send_keys("ggg")
    self.driver.find_element(By.CSS_SELECTOR, ".jshop_register:nth-child(1) > .control-group:nth-child(3)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("1@v.ru")
    self.driver.find_element(By.ID, "street").send_keys("ghfdf")
    self.driver.find_element(By.ID, "zip").send_keys("123456")
    self.driver.find_element(By.ID, "city").send_keys("dfghdfg")
    self.driver.find_element(By.ID, "state").send_keys("выпварвр")
    self.driver.find_element(By.CSS_SELECTOR, ".jshop_register:nth-child(1) > .control-group:nth-child(7)").click()
    self.driver.find_element(By.ID, "state").send_keys("j,kfcnm")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("999123456789")
    self.driver.find_element(By.NAME, "next").click()
    self.driver.find_element(By.ID, "payment_submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.NAME, "finish_registration").click()
    self.driver.find_element(By.NAME, "finish_registration").click()
  
